spinnsyn_bigquery_secret                   = "spinnsyn-bigquery-credentials"
sykepengesoknad_bigquery_secret            = "sykepengesoknad-bigquery-credentials"
sykepengesoknad_sak_status_bigquery_secret = "sykepengesoknad-sak-status-metrikk-credentials"
arkivering_oppgave_bigquery_secret         = "arkivering-oppgave-bigquery-credentials"
sykepengesoknad_datastream_secret          = "sykepengesoknad-datastream-credentials"