spinnsyn_bigquery_secret             = "spinnsyn-bigquery-credentials"
spinnsyn_datastream_secret           = "spinnsyn-datastream-credentials"
sykepengesoknad_bigquery_secret      = "sykepengesoknad-bigquery-credentials"
sykepengesoknad_datastream_secret    = "sykepengesoknad-datastream-credentials"
sak_status_metrikk_bigquery_secret   = "sak-status-metrikk-bigquery-credentials"
sak_status_metrikk_datastream_secret = "sak-status-metrikk-datastream-credentials"
arkivering_oppgave_bigquery_secret   = "arkivering-oppgave-bigquery-credentials"
arkivering_oppgave_datastream_secret = "arkivering-oppgave-datastream-credentials"
ditt_sykefravaer_datastream_secret   = "ditt-sykefravaer-datastream-credentials"

