name: 'Terraform'
on: push

jobs:
  terraform-plan-dev:
    name: 'terraform plan gcp-dev'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: Run 'terraform setup'
        uses: hashicorp/setup-terraform@v2

      - name: Run 'pwd'
        run: pwd

      - name: Run 'terraform init'
        run: terraform init

      - name: Run 'terraform fmt'
        run: terraform fmt -check

      - name: Run 'terraform validate'
        run: terraform validate

      - name: Run 'terraform plan'
        run: terraform plan

  terraform-plan-prod:
    name: 'terraform plan gcp-prod'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./prod

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SECRET_PROD }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: Run 'terraform setup'
        uses: hashicorp/setup-terraform@v2

      - name: Run 'pwd'
        run: pwd

      - name: Run 'terraform init'
        run: terraform init

      - name: Run 'terraform fmt'
        run: terraform fmt -check

      - name: Run 'terraform validate'
        run: terraform validate

      - name: Run 'terraform plan'
        run: terraform plan


  terraform-apply-dev:
      needs: terraform-plan-dev
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dev-')
      name: 'terraform apply gcp-dev'
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./dev

      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: Run 'terraform setup'
        uses: hashicorp/setup-terraform@v2

      - name: Run 'pwd'
        run: pwd

      - name: Run 'terraform init'
        run: terraform init