name: 'Terraform'
on: push

jobs:
  terraform-plan-dev:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: Run 'terraform setup'
        uses: hashicorp/setup-terraform@v2

      - name: Run 'pwd'
        run: pwd

      - name: Run 'terraform init'
        run: terraform init

      - name: Run 'terraform fmt'
        run: terraform fmt -check

      - name: Run 'terraform validate'
        run: terraform validate

      - name: Run 'terraform plan'
        run: terraform plan
